AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  ExtensionLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs20.x
      CompatibleArchitectures:
        - x86_64
    Metadata:
      BuildMethod: makefile

  TheFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x
      CodeUri: ./function
      Handler: src/app.lambdaHandler
      Timeout: 20
      Layers:
        - !Ref ExtensionLayer
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 minute)'
            Name: Schedule
            Enabled: true
